#ifndef ERROR_CODES_H
#define ERROR_CODES_H

enum ERROR_CODES
{
    OK,
    U1_ADAPTER_DISCONNECTED,
    U2_ADAPTER_DISCONNECTED,
    U1_AND_U2_DISCONNECTED,
    UNEXPECTED_ERROR,
    SYNCHRONISATION_ERROR,
    SERVER_ERROR,
};

#endif // ERROR_CODES_H
