#ifndef ERROR_CODES_H
#define ERROR_CODES_H

enum ERROR_CODE
{
    OK,
    SETTINGS_ERROR,
    DISCONNECTED,
    SERVER_ERROR,
    ROUTER_ERROR,
    REPOSITORY_ERROR,
    UNKNOWN_ERROR,
    PROGRAM_EXECUTION_ERROR
};

#endif // ERROR_CODES_H
